version: "3.8"
services:
 db:
  image: arm64v8/mysql:8
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: somewordpress
   MYSQL_DATABASE: wordpress
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: wordpress
 wordpress:
  depends_on:
   - db
  image: arm64v8/wordpress:6
  ports:
   - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_PASSWORD_FILE: /run/secret/wp_password.txt
   WORDPRESS_DB_NAME: wordpress
  secrets:
    - source: my_secret
      target: wordpress
   
secrets:
   my_secret:
     file: ./wp_password.txt
volumes:
 db_data: {}