version: '3.8'
services:
 db:
  image: arm64v8/mysql:8
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: "/run/secrets/wp_root"
   MYSQL_DATABASE: wordpress
   MYSQL_USER: "/run/secrets/wp_login"
   MYSQL_PASSWORD: "/run/secrets/wp_pass"
  secrets:
     - wp_login
     - wp_pass
     - wp_root 
 wordpress:
  depends_on:
   - db
  image: arm64v8/wordpress:6
  ports:
   - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: "/run/secrets/wp_login"
   WORDPRESS_DB_PASSWORD: "/run/secrets/wp_pass"
   WORDPRESS_DB_NAME: wordpress
  secrets:
     - wp_login
     - wp_pass
secrets:
  wp_login:
     external: true
  wp_pass:
     external: true
  wp_root:
     external: true

volumes:
 db_data: {}
