# This is a basic workflow to help you get started with Actions

name: CI
env:
  APPLICATION_NAME   : "MyFlasK"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print from Testing
        run: echo Hello, world!
      
      - name: Execute few command
        run: |
          echo "Hello 1"
          echo "Hello 2"
          echo "Application name is ${{ env.APPLICATION_NAME }}"

  my_deploy:

    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:

      - name: Print from Deployment
        run: echo Hello World from Deployment
          
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
